package view;

import java.util.ArrayList;
import model.Login;
import javax.swing.JOptionPane;
import service.Impl.NguoiDungServiceImpl;
import service.NguoiDungService;

public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    NguoiDungService qlLogin = new NguoiDungServiceImpl();
    ArrayList<Login> list = new ArrayList<>();

    public LoginView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMK = new javax.swing.JPasswordField();
        txtTenDN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMK.setBackground(new java.awt.Color(204, 255, 204));
        txtMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMK.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập mật khẩu"));
        getContentPane().add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 270, 63));

        txtTenDN.setBackground(new java.awt.Color(204, 255, 204));
        txtTenDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenDN.setBorder(javax.swing.BorderFactory.createTitledBorder("Tài khoản đăng nhập"));
        getContentPane().add(txtTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 270, 56));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Barlow Condensed Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Đăng Nhập");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 111, 39));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/dep.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkForm() {
        if (txtTenDN.getText().isEmpty() || txtMK.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (checkForm()) {
            String tenDN = txtTenDN.getText().trim();
            char[] pass = txtMK.getPassword();
            String mk = new String(pass).trim();
            list = qlLogin.LoginSearch(tenDN, mk);
            System.out.println(list);
            Login lgin = new Login(tenDN, mk, "", "");
            qlLogin.tenNV(lgin);
            System.out.println(lgin);
            System.out.println(lgin.getTenDangNhap());
            qlLogin.listLG();
            System.out.println(qlLogin.listLG());
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thất bại. Vui lòng kiểm tra lại tên tài khoản và mật khẩu!");
            } else if (list.size() == 1 && list.get(0).getChucVu().equals("QL")) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                this.setVisible(false);
                QuanLyView qlv = new QuanLyView();
                qlv.setVisible(true);
                System.out.println("Đã chạy đến đây");
            } else if (list.size() == 1 && list.get(0).getChucVu().equals("NV")) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                this.setVisible(false);
                NhanVienView nvv = new NhanVienView();
                nvv.setVisible(true);
                nvv.qlnd.tenNV(lgin);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên tài khoản và mật khẩu!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
